version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: clean_architecture_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:5.0
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Development123!"  # Contraseña básica para desarrollo
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  api:
    build:
      context: ../../
      dockerfile: docker/develop/Dockerfile
    container_name: api_container
    environment:
      - DATABASE_URL=mysql+pymysql://root:root_password@mysql:3306/clean_architecture_db
      - MONGODB_URI=mongodb://mongodb:27017
      - SQLSERVER_URL=mssql+pyodbc://sa:Development123!@sqlserver:1433
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - mongodb
      - sqlserver
    command: uvicorn main:app --host 0.0.0.0 --port 8000

volumes:
  mysql_data:
  mongo_data:
  sqlserver_data:

